function [sys, A, B, C, D] = ex2(m, c, k)

    A = [0 1; -k/m -c/m];       B = [0; 1/m];
    C = [1 0; 0 1; -k/m -c/m];  D = [0; 0; 1/m];

    sys = ss(...
        A, B, C, D,... 
        'StateName', {'y' ; 'dy'},... 
        'InputName', {'f(\omega)'},...
        'OutputName', {'y' ; 'dy'; 'ddy'});
end