function ex2(step, m, c, k)
    [w, wL, wH, rcp, asymL, asymH] = receptivity(step, m, c, k);


    sysDes = append(...
        "Receptância, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));

    figure; loglog(w, abs(rcp), wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        ['Magnitude Receptância \alpha(\omega)'],...
        [sysDes,...
         "Assíntota \omega \rightarrow 0",...
         "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_rcpAbs'),...
        '\omega [rad/s]', '\alpha(\omega)');


    figure; loglog(w, angle(rcp))
    savePlot(...
        ['Ângulo Receptância \alpha(\omega)'],...
        [sysDes],...
        append(sysVar, '_rcpAng'),...
        '\omega [rad/s]', '\alpha(\omega)');


    % H = tf([(+1)],[(-1*m) (1i*c) (k)]);
    % figure; bode(H)
    % savePlot([], [append("Receptância, wn = ", num2str(wn))], append('receptivityBode', num2str(wn)), '', '');
end