function ex3(step, m, c, k)
    [w, wL, wH, mbl, asymL, asymH] = mobility(step, m, c, k);


    sysDes = append(...
        "Mobilidade, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));

    figure; loglog(w, abs(mbl), wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        ['Magnitude Mobilidade y(\omega)'],...
        [sysDes,...
         "Assíntota \omega \rightarrow 0",...
         "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_mblAbs'),...
        '\omega [rad/s]', 'y(\omega)');
    
    
    figure; loglog(w, angle(mbl))
    savePlot(...
        ['Ângulo Mobilidade y(\omega)'],...
        [sysDes],...
        append(sysVar, '_mblAng'),...
        '\omega [rad/s]', 'y(\omega)');


    % H = tf([(-1i) (0)],[(-1*m) (1i*c) (k)]);
    % figure; bode(H)
    % savePlot([], [append("Mobilidade, wn = ", num2str(wn))], append('mobilityBode', num2str(wn)), '', '');
end