function ex4(step, m, c, k)
    [w, wL, wH, inr, asymL, asymH] = inertia(step, m, c, k);


    sysDes = append(...
        "Inertância, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));

    figure; loglog(w, abs(inr), wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        ['Magnitude Inertância A(\omega)'],...
        [sysDes,...
         "Assíntota \omega \rightarrow 0",...
         "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_inrAbs'),...
        '\omega [rad/s]', 'A(\omega)');


    figure; loglog(w, angle(inr))
    savePlot(...
        ['Ângulo Inertância A(\omega)'],...
        [sysDes],...
        append(sysVar, '_inrAng'),...
        '\omega [rad/s]', 'A(\omega)');


    % H = tf([(-1) (0) (0)],[(-1*m) (1i*c) (k)]);
    % figure; bode(H)
    % savePlot([], [append("Inertância, wn = ", num2str(wn))], append('inertiaBode', num2str(wn)), '', '');
end