function ex5(step, m, c, k)
    [w, wL, wH, rcp, asymL, asymH] = receptivity(step, m, c, k);
    sysDes = append(...
        "Assíntotas Receptância, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));

    figure; loglog(wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        [sysDes],...
        ["Assíntota \omega \rightarrow 0", "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_rcpAss'),...
        '\omega [rad/s]', '\alpha(\omega)');
    
    
    [w, wL, wH, mbl, asymL, asymH] = mobility(step, m, c, k);
    sysDes = append(...
        "Assíntotas Mobilidade, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));
    
    figure; loglog(wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        [sysDes],...
        ["Assíntota \omega \rightarrow 0", "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_mblAss'),...
        '\omega [rad/s]', 'y(\omega)');
    
    
    [w, wL, wH, inr, asymL, asymH] = inertia(step, m, c, k);
    sysDes = append(...
        "Assíntotas Inertância, m = ",num2str(m),...
        ", c = ",num2str(c),...
        " e k = ",num2str(k));
    sysVar = append("m",num2str(m),"c",num2str(c),"k",num2str(k));
    
    figure; loglog(wL, abs(asymL), '--', wH, abs(asymH), '--')
    savePlot(...
        [sysDes],...
        ["Assíntota \omega \rightarrow 0", "Assíntota \omega \rightarrow \infty"],...
        append(sysVar, '_inrAss'),...
        '\omega [rad/s]', 'A(\omega)');
end